apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: {{ .Values.clusterName }}-backup
  labels:
    {{- include "cnpg-database.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cluster.backup.schedule }}
  backupOwnerReference: self
  cluster:
    name: {{ .Values.clusterName }}