apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: {{ .Values.clusterName }}-backup
spec:
  schedule: {{ .Values.cluster.backup.schedule }}
  backupOwnerReference: self
  cluster:
    name: {{ .Values.clusterName }}