apiVersion: v1
data:
  username: {{.Values.authentication.clusterUser.username}}
  password: {{.Values.authentication.clusterUser.password}}
kind: Secret
metadata:
  name: {{.Values.global.clusterName}}-cluster-user
type: kubernetes.io/basic-auth