apiVersion: v1
labels:
  {{- include "cnpg-database.labels" . | nindent 4 }}
data:
  username: {{ .Values.authentication.clusterUser.username | b64enc }}
  password: {{ .Values.authentication.clusterUser.password | b64enc }}
kind: Secret
metadata:
  name: {{ .Values.clusterName }}-cluster-user
type: kubernetes.io/basic-auth