apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{.Values.global.clusterName}}
spec:
  description: "Database for" {{.Values.global.clusterName}}
  imageName: {{.Values.global.imageName}}
  instances: {{.Values.cluster.spec.instances}}
  postgresUID: 65534
  postgresGID: 65534
  startDelay: 300
  stopDelay: 300
  primaryUpdateStrategy: {{.Values.cluster.spec.primaryUpdateStrategy}}
  primaryUpdateMethod: {{.Values.cluster.spec.primaryUpdateMethod}}
  enablePDB: true

  postgresql:
    parameters:
      shared_buffers: 256MB
      pg_stat_statements.max: '10000'
      pg_stat_statements.track: all
      auto_explain.log_min_duration: '10s'

  bootstrap:
    initdb:
      database: gitlabhq_ci
      owner: gitlab
      secret:
        name: {{.Values.global.clusterName}}-cluster-user

  enableSuperuserAccess: {{.Values.authentication.clusterSuperUser.enable}}
  superuserSecret:
    name: {{.Values.global.clusterName}}-cluster-superuser

  storage:
    storageClass: {{.Values.cluster.storage.storageClass}}
    size: {{.Values.cluster.storage.size}}

  backup:
    barmanObjectStore:
      destinationPath: s3://{{.Values.global.clusterName}}/
      endpointURL: {{.Values.cluster.backup.endpointURL}}
      s3Credentials:
        accessKeyId:
          name: {{.Values.global.clusterName}}-backup-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: {{.Values.global.clusterName}}-backup-creds
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
        jobs: 2
    retentionPolicy: {{.Values.cluster.backup.retentionPolicy}}

  resources:
    requests:
      memory: {{.Values.resources.requests.memory}}
      cpu: {{.Values.resources.requests.cpu}}
