apiVersion: v1
labels:
  {{- include "cnpg-database.labels" . | nindent 4 }}
data:
  password: {{ .Values.authentication.clusterSuperUser.password }}
  username: {{ .Values.authentication.clusterSuperUser.username }}
kind: Secret
metadata:
  name: {{ .Values.clusterName }}-cluster-superuser
type: kubernetes.io/basic-auth