{{- define "insertDictionary" -}}
{{- $dict := .Values.postgresql.parameters -}}
{{- range $key, $value := $dict -}}
{{ $key }}: {{ $value }}
{{- end -}}
{{- end -}}


apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.clusterName }}
labels:
  {{- include "cnpg-database.labels" . | nindent 4 }}
spec:
  description: Database for {{ .Values.clusterName }}
  imageName: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
  instances: {{ .Values.cluster.spec.instances }}
  postgresUID: {{.Values.cluster.spec.postgresUID}}
  postgresGID: {{.Values.cluster.spec.postgresGID}}
  startDelay: 300
  stopDelay: 300
  primaryUpdateStrategy: {{ .Values.cluster.spec.primaryUpdateStrategy }}
  primaryUpdateMethod: {{ .Values.cluster.spec.primaryUpdateMethod }}
  enablePDB: {{.Values.cluster.spec.enablePDB}}

  postgresql:
    parameters:
      shared_buffers: {{ include "cnpg-database.sharedBufferSize" . }}
      {{ include "insertDictionary" . }}

      # pg_stat_statements.max: {{.Values.postgresql.parameters.pg_stat_statementsMax}}
      # pg_stat_statements.track: {{.Values.postgresql.parameters.pg_stat_statementsTrack}}
      # auto_explain.log_min_duration: {{.Values.postgresql.parameters.auto_explainLog_min_duration}}

  bootstrap:
    initdb:
      database: {{ .Values.databaseName }}
      owner: {{ .Values.authentication.clusterUser.username }}
      secret:
        name: {{ .Values.clusterName }}-cluster-user

  enableSuperuserAccess: {{ .Values.authentication.clusterSuperUser.enable }}
  superuserSecret:
    name: {{ .Values.clusterName }}-cluster-superuser

  storage:
    storageClass: {{ .Values.cluster.storage.storageClass }}
    size: {{ .Values.cluster.storage.size }}

  backup:
    barmanObjectStore:
      destinationPath: s3://{{ .Values.clusterName }}/
      endpointURL: {{ .Values.cluster.backup.endpointURL }}
      s3Credentials:
        accessKeyId:
          name: {{ .Values.clusterName }}-backup-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: {{ .Values.clusterName }}-backup-creds
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
        jobs: 2
    retentionPolicy: {{ .Values.cluster.backup.retentionPolicy }}

  resources:
    requests:
      memory: {{ .Values.resources.requests.memory }}
      cpu: {{ .Values.resources.requests.cpu }}
