apiVersion: v1
labels:
  {{- include "cnpg-database.labels" . | nindent 4 }}
data:
  password: {{ .Values.authentication.clusterSuperUser.password | b64enc | quote }}
  username: {{ .Values.authentication.clusterSuperUser.username | b64enc | quote }}
kind: Secret
metadata:
  name: {{ .Values.clusterName }}-cluster-superuser
type: kubernetes.io/basic-auth