apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Values.clusterName }}
  labels:
    cnpg.io/cluster: {{ .Values.clusterName }}
    app.kubernetes.io/monitored: "true"
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: {{ .Values.clusterName }}
  podMetricsEndpoints:
  - port: metrics