include:
  - component: $CI_SERVER_FQDN/ci-cd-components/helm/external-oci@0.7.0
    inputs:
      charts: ["cnpg-database"]
      registry: registry.supporterino.de
      library: supporterino
      username: robot$gitlab_ci
      password: $CI_USER_PASSWORD
      docs_commit_message: "docs: :memo: update helm README [skip-ci]"
