image:
  repository: ghcr.io/cloudnative-pg/postgresql
  tag: ""

clusterName: test-db
databaseName: dummy

cluster:
  spec:
    instances: 2
    primaryUpdateStrategy: unsupervised
    primaryUpdateMethod: switchover
    enablePDB: true
    postgresUID: 65534
    postgresGID: 65534
  backup:
    schedule: "0 10 0 * * *"
    endpointURL: http://minio.minio.svc.cluster.local:9000
    retentionPolicy: "30d"
    s3_access_key_id: ""
    s3_access_secret_key: ""
  storage:
    storageClass: nfs
    size: 10Gi

postgresql:
  parameters:
    pg_stat_statements.max: '10000'
    pg_stat_statements.track: all
    auto_explain.log_min_duration: '10s'

authentication:
  clusterSuperUser:
    enable: true
    username: ""
    password: ""
  clusterUser:
    username: ""
    password: ""

resources:
  requests:
    memory: 1Gi
    cpu: 100m